namespace: "markuman"
description: brings back Nessus Task Automation ✊
name: "nessus"
version: "0.0.6"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - nessus
    - collection
    - security
repository: https://gitea.osuv.de/m/nessus
issues: https://github.com/markuman/nessus